create or replace PROCEDURE EDITAR_CANTIDAD_FACTURA(id_linea_editar in LINEAPEDIDO.ID_LINEA_PEDIDO%TYPE, cantidad_editar in LINEAPEDIDO.CANTIDAD_PEDIDO%TYPE)IS
BEGIN
  UPDATE LINEAPEDIDO SET CANTIDAD_PEDIDO = cantidad_editar WHERE ID_LINEA_PEDIDO = id_linea_editar;
END;